### ISSUE TITLE
部署上去 执行定时任务日志报错

### ISSUE THREAD

**Issue by Imtonoo** [canmind/fastdfs-zyc#2]
错误日志如下：
是不是读取
 <server>
          <ip>192.168.40.53</ip>
          <username>root</username>
          <password>123456</password>
          <logpath>/usr/local/nginx-1.10.0/logs/</logpath>
</server>

的 <logpath>/usr/local/nginx-1.10.0/logs/</logpath>的问题呀，但是我们的dfs没有使用nginx，应该指向什么日志纳

[16:18:00.002] 16:18:00,002  INFO JobServiceImpl:56 - group minute data upate begin...
[16:18:00.003] 16:18:00,002  INFO JobServiceImpl:95 - network_timeout=30000ms
[16:18:00.003] 16:18:00,003  INFO JobServiceImpl:96 - charset=ISO8859-1
[16:18:00.008] 16:18:00,007  INFO JobServiceImpl:108 - group count: 3
[16:18:00.012] 16:18:00,012 ERROR TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task.
               java.io.IOException: byte array length: 612 is invalid!
               	at org.csource.fastdfs.ProtoStructDecoder.decode(ProtoStructDecoder.java:38)
               	at org.csource.fastdfs.TrackerClient.listStorages(TrackerClient.java:752)
               	at org.csource.fastdfs.TrackerClient.listStorages(TrackerClient.java:661)
               	at cn.me.fdfs.service.impl.JobServiceImpl.getGroupInfoByMinute(JobServiceImpl.java:112)
               	at cn.me.fdfs.service.impl.JobServiceImpl.updateGroupByMinute(JobServiceImpl.java:57)
               	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
               	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
               	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               	at java.lang.reflect.Method.invoke(Method.java:606)
               	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
               	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
               	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
               	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
               	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
               	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
               	at com.sun.proxy.$Proxy56.updateGroupByMinute(Unknown Source)
               	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
               	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
               	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               	at java.lang.reflect.Method.invoke(Method.java:606)
               	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64)
               	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53)
               	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
               	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
               	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
               	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
               	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
               	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
               	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
               	at java.lang.Thread.run(Thread.java:745)

**Comment by 0312birdzhang** [comment]
请问你是如何解决的？

**Comment by 0312birdzhang** [comment]
用最新的fastdfs-client-java包就可以了
